# Generated by Django 6.0.2 on 2026-03-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="species",
            field=models.CharField(
                choices=[
                    ("dog", "Собака"),
                    ("cat", "Кіт"),
                    ("parrot", "Папуга"),
                    ("hamster", "Хомʼяк"),
                    ("rabbit", "Кролик"),
                    ("other", "Інше"),
                ],
                default="dog",
                max_length=20,
                verbose_name="Вид",
            ),
        ),
    ]
