# Generated by Django 6.0.2 on 2026-03-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Articles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Назва новини"),
                ),
                ("anons", models.CharField(max_length=250, verbose_name="Анонс")),
                ("full_text", models.TextField(verbose_name="Новина")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата публікації"
                    ),
                ),
            ],
            options={
                "verbose_name": "Новини",
                "verbose_name_plural": "Новини",
            },
        ),
    ]
