# Generated by Django 6.0.2 on 2026-03-03 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
        ("profiles", "0003_alter_pet_species"),
    ]

    operations = [
        migrations.AddField(
            model_name="articles",
            name="author_pet",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="news",
                to="profiles.pet",
                verbose_name="Автор (тваринка)",
            ),
            preserve_default=False,
        ),
    ]
