# Generated by Django 6.0.2 on 2026-03-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Ім'я тваринки"),
                ),
                (
                    "species",
                    models.CharField(
                        max_length=50, verbose_name="Вид (кіт, собака тощо)"
                    ),
                ),
                ("birth_date", models.DateField(verbose_name="Дата народження")),
                (
                    "photo",
                    models.ImageField(
                        default="default_pet.jpg", upload_to="pets_photos/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bio", models.TextField(blank=True, max_length=500)),
                ("location", models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
