# Generated by Django 6.0.2 on 2026-03-06 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_alter_pet_species"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="name",
            field=models.CharField(blank=True, max_length=50, verbose_name="Ім'я"),
        ),
    ]
