# Generated by Django 6.0.2 on 2026-03-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='old_owners',
            field=models.ManyToManyField(blank=True, related_name='past_pets', to='profiles.profile'),
        ),
    ]
