# Generated by Django 6.0.2 on 2026-03-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_pet_old_owners'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='status',
            field=models.CharField(choices=[('active', 'З господарем'), ('adoption', 'Шукає дім'), ('adopted', 'В новій сім’ї')], default='active', max_length=20, verbose_name='Статус'),
        ),
    ]
