# Generated by Django 6.0.2 on 2026-03-09 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_alter_pet_status_adoptionrequest'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='adoptionrequest',
            unique_together=set(),
        ),
    ]
