# Generated by Django 6.0.2 on 2026-03-09 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_alter_adoptionrequest_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdoptionRequest',
        ),
    ]
